name: Bump version

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install commitizen
        run: pip install commitizen

      - name: Bump version
        id: cz_bump
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "Bumping minor version"
            cz bump --changelog --increment minor
          elif [[ "$BRANCH_NAME" == "hotfix" ]]; then
            echo "Bumping patch version"
            cz bump --changelog --increment patch
          else
            echo "No version bump for branch $BRANCH_NAME"
            exit 0
          fi

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          changelog_increment_filename: body.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: "${{ steps.cz_bump.outputs.tag_name }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
